name: Update Products

on:
  schedule:
    - cron: "0 6 * * *"  # daily

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run updater
        run: node updateProducts.js

      - name: Commit updated products
        run: |
          git config --global user.name "Manish 2988"
          git config --global user.email "manishshinde8829@gmail.com"
          git add products.json
          git commit -m "update products" || echo "No changes"
          git push
